"""migration of post table

Revision ID: 74637c0fff0b
Revises: 7e323af0b329
Create Date: 2019-03-12 09:44:44.065369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74637c0fff0b'
down_revision = '7e323af0b329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
